version: "3.8"
services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./scorm-package:/usr/share/nginx/html
    restart: unless-stopped

  # image-generator:
  #   image: stabilityai/stable-diffusion-webui
  #   ports:
  #     - "5000:7860"
  #   volumes:
  #     - ./generated-images:/output
  #   restart: unless-stopped
